// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ikcozxvsqbjkvwtylpxe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlrY296eHZzcWJqa3Z3dHlscHhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3NzkwMzQsImV4cCI6MjA2NjM1NTAzNH0.wZfqy1PvA0luo3vUjImyovEQId1Ml6lV6jdyEseYWdM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);